from __future__ import annotations
from typing import Protocol
from redteamrl.types import TaskSpec

class Sandbox(Protocol):
    def reset(self, spec: TaskSpec) -> None:
        ...
    def read_file(self, path: str) -> str:
        ...
    def list_dir(self, path:str) -> str:
        ...
    def close(self) -> None:
        ...